-- Seed repo defaults once; runtime /addpublisher edits survive redeploys.
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ဆုပြည့်စုံထွန်းစာပေ','ဆုပြည့်စုံထွန်းစာပေ','https://www.facebook.com/share/1BiTBycHXq/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('Quality Publishing House','qualitypublishinghouse','https://www.facebook.com/share/1EntVn4HfB/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('Little Yangon Publication','littleyangonpublication','https://www.facebook.com/share/1ESC8w8rCA/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ကိုလတ်စာပေ','ကိုလတ်စာပေ','https://www.facebook.com/share/18ADGjZefz/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ဆောင်းစုရတီ','ဆောင်းစုရတီ','https://www.facebook.com/share/1H4j1GuyVZ/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ပန်းဆက်လမ်း','ပန်းဆက်လမ်း','https://www.facebook.com/share/1F1oYnQpGn/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('လဝန်းရိပ်စာပေ','လဝန်းရိပ်စာပေ','https://www.facebook.com/share/192oeNpaRx/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ဇော်ဂျီဖိုလ်ဝင်စာအုပ်တိုက်','ဇော်ဂျီဖိုလ်ဝင်စာအုပ်တိုက်','https://www.facebook.com/share/1LeH4yuYG4/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('လင်းသစ်ရောင်စဉ် စာအုပ်တိုက်','လင်းသစ်ရောင်စဉ်စာအုပ်တိုက်','https://www.facebook.com/share/18tm8KJevR/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('Linn Thit Pyi လင်းသစ်ပြည်စာပေ','linnthitpyiလင်းသစ်ပြည်စာပေ','https://www.facebook.com/share/1DUqptCDtp/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ဗဂျီအိမ်စာပေ','ဗဂျီအိမ်စာပေ','https://www.facebook.com/share/17hDhAshDf/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ဘဝတက္ကသိုလ်','ဘဝတက္ကသိုလ်','https://www.facebook.com/share/17rKbZEao9/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('10A','10a','https://www.facebook.com/share/18Ftn33HDn/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('Wisdom House','wisdomhouse','https://www.facebook.com/share/1DBzy9RPsB/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ကေဇော် စာအုပ်တိုက်','ကေဇော်စာအုပ်တိုက်','https://www.facebook.com/share/1HfNJYKfSG/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ထိခေါင်','ထိခေါင်','https://www.facebook.com/share/1BnbwMKuE1/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ထွန်းတောက်စာအုပ်တိုက်','ထွန်းတောက်စာအုပ်တိုက်','https://www.facebook.com/profile.php?id=61574375881243&mibextid=ZbWKwL',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ဒီရေကမ်ူစာပေ','ဒီရေကမ်ူစာပေ','https://www.facebook.com/share/14jdSYoEyqk/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('နှစ်ကာလများ','နှစ်ကာလများ','https://www.facebook.com/share/1G5kuzDGpM/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('The Cat','thecat','https://www.facebook.com/share/1AX4d1ST3o/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ဆုပြည့်စုံထွန်း','ဆုပြည့်စုံထွန်း','https://www.facebook.com/share/1BiTBycHXq/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ဆုပြည်စုံထွန်းစာပေ','ဆုပြည်စုံထွန်းစာပေ','https://www.facebook.com/share/1BiTBycHXq/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ဆောင်းစုရတီ','ဆောင်းစုရတီ','https://www.facebook.com/share/1H4j1GuyVZ/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ဆောင်းစုရတီစာပေ','ဆောင်းစုရတီစာပေ','https://www.facebook.com/share/1H4j1GuyVZ/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ွQuality Publishing House','ွqualitypublishinghouse','https://www.facebook.com/share/1EntVn4HfB/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('Little Yangon Publcation','littleyangonpublcation','https://www.facebook.com/share/1ESC8w8rCA/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('ပန်းဆက်လမ်းစာပေ','ပန်းဆက်လမ်းစာပေ','https://www.facebook.com/share/1F1oYnQpGn/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('လင်းသစ်ရောင်စဉ်','လင်းသစ်ရောင်စဉ်','https://www.facebook.com/share/18tm8KJevR/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('Linn Thit Pyi လင်းသစ်ပြည် စာပေ','linnthitpyiလင်းသစ်ပြည်စာပေ','https://www.facebook.com/share/1DUqptCDtp/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('စာရိပ်မြိုင် စာပေ','စာရိပ်မြိုင်စာပေ','https://www.facebook.com/share/19MApsWDbJ/',0);
INSERT OR IGNORE INTO publisher_links(name,name_n,url,updated_at) VALUES('စာရိပ်မြိုင်စာပေ','စာရိပ်မြိုင်စာပေ','https://www.facebook.com/share/19MApsWDbJ/',0);
